export const provincias = [
{
id: 'panama-oeste',
nombre: 'Panamá Oeste',
banner: {
tipo: 'video',
src: '/videos/panamaOeste/VideoBannerPanamaOeste.av1.mp4',
alt: 'Vista del destino de Panamá Oeste',
},
descripcionCorta:
'Panamá Oeste es el respiro necesario que te saca de la ciudad para llevarte a la brisa fresca del Cerro Campana en menos de una hora. Disfruta de un destino que combina la tranquilidad de la vida de campo con playas que ofrecen el escape perfecto para cada fin de semana.',
ubicacionProvincia: {
src: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d913425.1409493805!2d-80.52579866505599!3d8.800879120442339!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e5363df156c409f%3A0x1ba52dd719570414!2sPanam%C3%A1%20Oeste%20Province!5e1!3m2!1sen!2spa!4v1779308611155!5m2!1sen!2spa',
},
actividades: [
  'Surf',
  'Senderismo',
  'Fotografía',
  'Camping',
  'Kitesurf',
  'Windsurf',
  'Disfrutar de la playa',
  'Paseos por la costa',
  'Fotografía de paisajes',
  'Pesca recreativa',
  'Picnic frente al mar',
  'Turismo de naturaleza',
  'Escapadas de fin de semana',
  'Gastronomía local',
  'Pesca artesanal',
  'Gastronomía frente al mar',
  'Paseos costeros',
  'Golf',
  'Fotografía costera',
  'Clases de surf',
  'Yoga',
  'Gastronomía',
  'Bodyboard',
  'Pesca',
  'Pícnic',
  'Avistamiento de aves',
  'Paddleboard',
],
displayMode: 'sites-only',
directSiteIds: ['playa-san-carlos', 'coronado', 'playa-el-palmar', 'punta-chame', 'playa-malibu', 'playa-sea-cliff', 'gorgona', 'veracruz'],
},
]
