export const provincias = [
  {
    id: 'colon',
    nombre: 'Colón',
    banner: {
      tipo: 'video',
      src: '/videos/colon/ColonBanner.av1.mp4',
      alt: 'Vista del destino de Colón',
    },
    descripcionCorta:
      'Colón combina historia, Caribe, islas y paisajes vinculados al Canal de Panamá. Es un destino ideal para conocer fortificaciones, playas y destinos naturales con identidad propia.',
    ubicacionProvincia: {
      src: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d797024.4492928673!2d-80.63741947944797!3d9.139537273998036!2m3!1f0!2f0!3f0!2m3!1i1024!2i768!4f13.1!3m3!1m2!1s0x8fab25f6fbeed405%3A0xbc032eadbbacf29a!2sCol%C3%B3n%20Province!5e1!3m2!1sen!2spa!4v1778602312976!5m2!1sen!2spa',
    },
    actividades: [
      'Senderismo',
      'Avistamiento de aves',
      'Observación de flora',
      'Fotografía',
      'Camping',
      'Ruinas coloniales',
      'Miradores',
      'Observación de buques',
      'Centro de visitantes',
      'Turismo educativo',
      'Visita guiada',
      'Visita al entorno canalero',
      'Paseo en bote',
      'Snorkel',
      'Buceo',
      'Kayak',
      'Pesca deportiva',
      'Gastronomía',
      'Iglesia de San Felipe',
      'Festividades religiosas',
    ],
    displayMode: 'zones-only',
    targets: [
      {
        id: 'costa-abajo',
        type: 'zone',
        zoneId: 'costa-abajo',
        nombre: 'Costa Abajo',
        descripcion: 'Historia, naturaleza y Canal de Panamá en Colón.',
        imagen: '/images/destinations/colon/costa-abajo/castillo-san-lorenzo/bg-castillo-san-lorenzo.webp',
      },
      {
        id: 'costa-arriba',
        type: 'zone',
        zoneId: 'costa-arriba',
        nombre: 'Costa Arriba',
        descripcion: 'Caribe histórico y cultural de Colón.',
        imagen: '/images/destinations/colon/costa-arriba/portobelo/bg-portobelo.webp',
      },
    ],
  },
]
