export const provincias = [
  {
    id: 'chiriqui',
    nombre: 'Chiriquí',

    banner: {
      tipo: 'video',
      src: '/videos/chiriqui/VideoBannerChiriqui.av1.mp4',
      alt: 'Vista de la provincia de Chiriquí',
    },

    descripcionCorta:
      'Chiriquí combina montañas, playas, cafetales y pueblos de clima fresco en una sola provincia. Es un destino ideal para quienes buscan naturaleza, aventura y experiencias auténticas en el occidente panameño.',

    ubicacionProvincia: {
      src: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1597092.60755608!2d-83.60221811003264!3d8.432382055975108!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8fa5098873daff19%3A0x89cdd65056b29fe9!2sChiriqu%C3%AD%20Province!5e1!3m2!1sen!2spa!4v1778607596126!5m2!1sen!2spa',
    },
    actividades: [
      'Senderismo',
      'Pesca deportiva',
      'Paseo en bote',
      'Islas',
      'Ballenas',
      'Snorkel',
      'Kayak',
      'Fotografía',
      'Fauna marina',
      'Excursión al golfo',
      'Café',
      'Compras artesanales',
      'Gastronomía',
      'Parque central',
      'Mercados locales',
      'Vida nocturna',
      'Fincas agrícolas',
      'Aves',
      'Productos agrícolas',
      'Paisajes',
      'Compras',
      'Parques',
      'Eventos',
      'Mercados',
      'Base de viaje',
      'Los Cangilones',
      'Picnic',
      'Cascadas',
      'Turismo rural',
      'Atardecer',
      'Tortugas',
      'Brisa marina',
      'Naturaleza',
      'Escapada',
      'Cabalgata',
      'Relajación',
      'Familia',
      'Playa',
      'Historia',
      'Paseo',
      'Amanecer',
      'Flora y fauna',
      'Senderismo 4x4',
      'Estrellas',
      'Bosque nuboso',
      'Aventura',
    ],

    directSiteIds: [
      'boquete-centro',
      'gualaca',
      'volcan-baru',
      'david-centro',
      'cerro-punta-centro',
      'boca-chica',
      'playa-barqueta',
      'playa-las-lajas',
      'puerto-armuelles',
    ],
    displayMode: 'sites-only',
  },
]
