export const provinceMedia = [
    {
        id: 'bocas-del-toro',
        nombre: 'Bocas del Toro',
        path: '/provincias/bocas-del-toro',
        banner: '/videos/bocasDelToro/bocasBanner.av1.mp4',
        poster: '/maps/provinces/bocas-del-toro.avif',
    },
    {
        id: 'chiriqui',
        nombre: 'Chiriquí',
        path: '/provincias/chiriqui',
        banner: '/videos/chiriqui/VideoBannerChiriqui.av1.mp4',
        poster: '/maps/provinces/chiriqui.avif',
    },
    {
        id: 'cocle',
        nombre: 'Coclé',
        path: '/provincias/cocle',
        banner: '/videos/cocle/CocleBanner.av1.mp4',
        poster: '/maps/provinces/cocle.avif',
    },
    {
        id: 'colon',
        nombre: 'Colón',
        path: '/provincias/colon',
        banner: '/videos/colon/ColonBanner.av1.mp4',
        poster: '/maps/provinces/colon.avif',
    },
    {
        id: 'darien',
        nombre: 'Darién',
        path: '/provincias/darien',
        banner: '/videos/darien/DarienBanner.av1.mp4',
        poster: '/maps/provinces/darien.avif',
    },
    {
        id: 'herrera',
        nombre: 'Herrera',
        path: '/provincias/herrera',
        banner: '/videos/herrera/HerreraBanner.av1.mp4',
        poster: '/maps/provinces/herrera.avif',
    },
    {
        id: 'los-santos',
        nombre: 'Los Santos',
        path: '/provincias/los-santos',
        banner: '/videos/los_santos/Los_santos_Banner.av1.mp4',
        poster: '/maps/provinces/los-santos.avif',
    },
    {
        id: 'panama',
        nombre: 'Panamá',
        path: '/provincias/panama',
        banner: '/videos/panama/PanamaBanner.av1.mp4',
        poster: '/maps/provinces/panama.avif',
    },
    {
        id: 'panama-oeste',
        nombre: 'Panamá Oeste',
        path: '/provincias/panama-oeste',
        banner: '/videos/panamaOeste/VideoBannerPanamaOeste.av1.mp4',
        poster: '/maps/provinces/panama-oeste.avif',
    },
    {
        id: 'veraguas',
        nombre: 'Veraguas',
        path: '/provincias/veraguas',
        banner: '/videos/veraguas/VeraguasBanner.av1.mp4',
        poster: '/maps/provinces/veraguas.avif',
    },
    {
        id: 'comarca-guna-yala',
        nombre: 'Guna Yala',
        path: '/provincias/comarca-guna-yala',
        banner: '/videos/guna_yala/GunaYalaBanner.av1.mp4',
        poster: '/maps/provinces/comarca-guna-yala.avif',
    },
]
